export const enum ORDER_STATUS {
  PENDING = 'PENDING',
  EDITING = 'EDITING',
  PENDING_RECEIVE = 'PENDING_RECEIVE',
  INTRANSIT = 'INTRANSIT',
  COLLECTING = 'COLLECTING',
  DELIVERING = 'DELIVERING',
  READY_TO_DISPATCH = 'READY_TO_DISPATCH',
  ARRIVED = 'ARRIVED',
  READY_TO_UNLOAD = 'READY_TO_UNLOAD',
  READY_TO_PICK = 'READY_TO_PICK',
  PICKING = 'PICKING',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  SHIPPING = 'SHIPPING',
  DONE = 'DONE'
}

export const enum ORDER_PRODUCT_STATUS {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  INTRANSIT = 'INTRANSIT',
  ARRIVED = 'ARRIVED',
  READY_TO_COLLECT = 'READY_TO_COLLECT',
  READY_TO_DELIVER = 'READY_TO_DELIVER',
  READY_TO_UNLOAD = 'READY_TO_UNLOAD',
  READY_TO_PICK = 'READY_TO_PICK',
  PICKING = 'PICKING',
  UNLOADING = 'UNLOADING',
  UNLOADED = 'UNLOADED',
  COLLECTED = 'COLLECTED',
  DELIVERED = 'DELIVERED',
  PUTTING_AWAY = 'PUTTING_AWAY',
  RELEASED = 'RELEASED',
  STORED = 'STORED'
}

export const enum ORDER_VAS_STATUS {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  READY_TO_PROCESS = 'READY_TO_PROCESS',
  PROCESSING = 'PROCESSING'
}
