export const VAS_TARGET_TYPES = {
  BATCH_NO_TYPE: 'BATCH_NO',
  PRODUCT_TYPE: 'PRODUCT',
  BATCH_AND_PRODUCT_TYPE: 'BATCH_AND_PRODUCT_TYPE',
  ETC_TYPE: 'ETC'
}

export const VAS_TYPES = {
  MATERIALS: 'MATERIALS',
  SERVICE: 'SERVICE'
}
